concession_back_index:
    path: /concessions
    controller: App\Domain\Concession\Controller\Web\ConcessionController::index
concession_back_show:
    path: /concessions/{id}
    controller: App\Domain\Concession\Controller\Web\ConcessionController::show
    requirements:
        id: '\d+'
concession_back_create:
    path: /concession/create
    controller: App\Domain\Concession\Controller\Web\ConcessionController::create
concession_back_export:
    path: /concessions/export
    controller: App\Domain\Concession\Controller\Web\ConcessionController::export
concession_back_update:
    path: /concessions/{id}/update
    controller: App\Domain\Concession\Controller\Web\ConcessionController::update
concession_back_delete:
    path: /concessions/{id}/delete
    controller: App\Domain\Concession\Controller\Web\ConcessionController::delete