user_back_index:
    path: /users
    controller: App\Domain\User\Controller\Web\UserController::index

user_back_show:
    path: /users/{id}
    controller: App\Domain\User\Controller\Web\UserController::show
    requirements:
        id: '\d+'

user_back_export:
    path: /users/export
    controller: App\Domain\User\Controller\Web\UserController::export

user_back_create:
    path: /users/create
    controller: App\Domain\User\Controller\Web\UserController::create

user_back_update:
    path: /users/{id}/update
    controller: App\Domain\User\Controller\Web\UserController::update
    requirements:
        id: '\d+'
user_back_delete:
    path: /users/{id}/delete
    controller: App\Domain\User\Controller\Web\UserController::delete
    requirements:
        id: '\d+'
user_back_login:
    path: /login
    controller: App\Domain\User\Controller\Web\UserController::login

user_back_logout:
    path: /logout

user_back_self:
    path: /users/self
    controller: App\Domain\User\Controller\Web\UserController::self

user_back_self_update:
    path: /users/self/update
    controller: App\Domain\User\Controller\Web\UserController::selfUpdate

vehicle_back_index:
    path: /users/{id}/vehicles
    controller: App\Domain\User\Controller\Web\VehicleController::index
    requirements:
        id: '\d+'

vehicle_back_create:
    path: /users/{id}/vehicles/create
    controller: App\Domain\User\Controller\Web\VehicleController::create
    requirements:
        id: '\d+'

vehicle_back_delete:
    path: /users/{user_id}/vehicles/{id}
    controller: App\Domain\User\Controller\Web\VehicleController::delete
    requirements:
        id: '\d+'