doctrine:
    dbal:
        url: "%env(resolve:DATABASE_URL)%"
        schema_filter: '~^(?!messenger_messages)~'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            user:
                type: xml
                dir: "%kernel.project_dir%/config/settings/domain/user/mapping"
                prefix: App\Domain\User\Entity
                is_bundle: false
                alias: UserDomain
            concession:
                type: xml
                dir: "%kernel.project_dir%/config/settings/domain/concession/mapping"
                prefix: App\Domain\Concession\Entity
                is_bundle: false
                alias: ConcessionDomain
            vehicle_model:
                type: xml
                dir: "%kernel.project_dir%/config/settings/domain/vehicle_model/mapping"
                prefix: App\Domain\VehicleModel\Entity
                is_bundle: false
                alias: VehicleModelDomain
            export:
                type: xml
                dir: "%kernel.project_dir%/config/settings/domain/export/mapping"
                prefix: App\Domain\Export\Entity
                is_bundle: false
                alias: ExportDomain
            vehicle:
                type: xml
                dir: "%kernel.project_dir%/config/settings/domain/user/mapping"
                prefix: App\Domain\User\Entity
                is_bundle: false
                alias: VehicleDomain